### ISSUE TITLE
Looks like Daft have changed their HTML/DOM layout

### ISSUE THREAD

**Issue by niallrmurphy** [TheJokersThief/daft-scraper#12]
No results are returned, either by the raw API, or by the search CLI, for some simple searches:

niallm@localhost daft-scraper-main $ /usr/local/bin/poetry run daft search --max-pages 1 property-for-rent --location cork --location galway
id    price    title    propertyType    url
----  -------  -------  --------------  -----

(It finds results, but they don't contain any data, which is consistent with parsing "X results found" but not any of the actual details.)

**Comment by TheJokersThief** [comment]
So it's not a website change but my own mistake on this one 🤦‍♀️ I'd changed from using a dictionary to an object when I added something new and didn't update the CLI or readme example so it was accessing the info wrong and just returning `None`. I've already got a fix done up, should be sorted soon :) 

Thanks for the issue!

**Comment by niallrmurphy** [comment]
Thanks for the fix!
