### ISSUE TITLE
Feature: Include Purchase propertyTypes

### ISSUE THREAD

**Issue by Avitus27** [TheJokersThief/daft-scraper#15]
https://github.com/TheJokersThief/daft-scraper/blob/e23a84f0a83b3b219e100d50431958f3df9a631e/daft_scraper/search/options.py#L58
This list works for rented but the list for purchasing seems different 
![image](https://user-images.githubusercontent.com/5860120/104177059-1ab90b80-5400-11eb-89fa-afedc658c6ff.png)
Might be worth including these types as possible options when doing a property-for-sale search
e.g.
```bash
$ poetry run daft search --max-pages 5 property-for-sale --location cork --max-price 200000 --sort priceAsc --property-type detached
```

**Comment by TheJokersThief** [comment]
Good catch :) Yep, those need to be added, thank you!
